// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oahllcmgpeyncgaeiaqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9haGxsY21ncGV5bmNnYWVpYXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMDUzNTksImV4cCI6MjA1NTc4MTM1OX0.gaMHNBJHLziTJYnR6dN8SV7Ay7J1l11UrhnRCwTBLwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);